### ISSUE TITLE
UnicodeEncode Error in fetchini/main.py

### ISSUE THREAD

**Issue by William-Hill** [IS-ENES-Data/esgf-prepare#6] opened 2017-08-08 00:33 UTC
There's an encoding error occurring when attempting to write to the outfile in the write_content() function.

Stack trace:

Fetching new esg.<project>.ini files from github:
   Running 'esgprep fetch-ini' -k:
   
Fetching "esg.<project>.ini":  50% |##########################                          | 8/16 filesTraceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/bin/esgprep", line 11, in <module>
    load_entry_point('esgprep==2.7.9', 'console_scripts', 'esgprep')()
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgprep/esgprep.py", line 417, in run
    main.main(args)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgprep/fetchini/main.py", line 140, in main
    write_content(outfile, content)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgprep/fetchini/main.py", line 63, in write_content
    f.write(content)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 1873: ordinal not in range(128)

**Comment by soay** [comment] 2017-08-08 12:49
The cause for this error is the trailing blank after the version_pattern in esg.cmip6.ini. Fixed in devel.

**Comment by glevava** [comment] 2017-08-15 16:13
I don't understand why fix the issue through esgprep if it comes from the original ini files... I prefer to correct the esg.cmip6.ini encoding issue and use esgprep fetch-ini to detect such kind of issues in the fetched files. 
In addition this will tested in the test suite I'm coding now for esgprep.

**Closed** 2017-10-10 08:53 UTC
